catalog/urls.py
from django.urls import path 
from django.urls import re_path 
from . import views 
from django.contrib.auth.decorators import login_required
from django.conf import settings 
from django.conf.urls.static import static
 

urlpatterns = [ 

    path('',views.index,name='index'), 
    path('index/',views.index,name='index'), 
    path("probando/<int:par1>",views.probando,name="probando"),
    path("autores/<int:par2>",views.autores,name="autores"),
    path('books/', views.BookListView.as_view(), name='books'),
    path('author/', views.AuthorListView.as_view(), name='author'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('calculator/', views.Calculator.calculator, name='calculator'),
    path('calculator/<int:numero>', views.Calculator.calculator, name='calculator'),
    path('calculator/<str:signo>', views.Calculator.calculator, name='calculator'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('prestado/', views.TotalLibrosPrestadosListView.as_view(), name='prestado'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('formu/', views.formularioCompleto, name='formu'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('formuExamen/', views.formularioExamen, name='formuExamen'),
    path('generarPDF/<int:id>', views.generarPdf, name='generarPDF'),
    path('register', views.register, name='register'),
    path('crear-perfil', views.creacion_perfil, name='crear-perfil'),
    path('crear-mensaje', views.mandar_mensajes, name='crear-mensaje'),
    path('bookAPI', views.BookView.as_view(), name='bookAPI'), 
    path('bookDetailApi/<int:pk>', views.BookDetailApi.as_view(), name='bookDetailApi'), 
    path('gestion_mensaje/<int:pk>', views.gestion_mensaje2, name='gestion_mensaje'), 
    path('mensajes_list', views.MensajesListView.as_view(), name='mensajes_list'),
    path('administrar_mensajes', views.AdministrarListView.as_view(), name='administrar_mensajes'), 
    path('mensajes/<int:pk>/update/', views.MensajesUpdate.as_view(), name='mensajes-update'),
    path('mensajes/<int:pk>/delete/', views.MensajesDelete.as_view(), name='mensajes-delete'),


    # re_path(r'^$',login_required(views.index),name='index')


] 

libreriaClase/urls.py
from django.contrib import admin 
from django.urls import path 
from django.urls import include 
from django.views.generic import RedirectView 
from django.conf import settings 
from django.conf.urls.static import static 

  

urlpatterns = [ 

    path('admin/', admin.site.urls), 
    path('catalog/', include('catalog.urls')), 
    path('',RedirectView.as_view(url='/catalog/',permanent=True)), 
    path('accounts/', include('django.contrib.auth.urls')),

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid # Requerida para las instancias de libros únicos
# Create your models here.
from django.contrib.auth.models import User 
from datetime import date

from django.core.validators import FileExtensionValidator 


 
class usu(models.Model): 
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    comentario= models.TextField(max_length=200) 

class Person(models.Model): 
    first_name = models.CharField(max_length=150) 
    last_name = models.CharField(max_length=150) 
    age = models.IntegerField() 

class Genre(models.Model):

    name = models.CharField(max_length=200, help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)")

    def __str__(self):
     
        return self.name
    



class Book(models.Model):
 

    title = models.CharField(max_length=200)

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    # 'Author' es un string, en vez de un objeto, porque la clase Author aún no ha sido declarada.

    summary = models.TextField(max_length=1000, help_text="Ingrese una breve descripción del libro")

    isbn = models.CharField('ISBN',max_length=13, help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField(Genre, help_text="Seleccione un genero para este libro")
    # ManyToManyField, porque un género puede contener muchos libros y un libro puede cubrir varios géneros.
    # La clase Genre ya ha sido definida, entonces podemos especificar el objeto arriba.
    
    portada = models.ImageField(upload_to='catalog/media/imagenes/' ,null=True)

    video = models.FileField(upload_to='catalog/media/videos/',null=True,validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv'])])

    ficheros = models.FileField(upload_to="catalog/media/pdf/" , null=True)


    def __str__(self):
        
        return self.title

    #Devuelve una URL a una instancia particular de book
    def get_absolute_url(self):
        #Reverse es parecido a un join que lo hace mediante el urls y el args
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
  
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre' 




class BookInstance(models.Model):
   
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Disponibilidad del libro')

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank = True)

    class Meta:
        ordering = ["due_back"]
#Nombre de permiso y descripcion
        permissions = (("can_mark_returned", "Set book as returned"),
                       ("can_generate_pdf", "Generate PDF"),
                       ("permiso1","Crear Usuario"),
                       ("permiso2","Crear Perfil Usuario"),
                       ("permiso3","Gestion Mensajes"))
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
      
        return '%s (%s)' % (self.id,self.book.title)
    
class Author(models.Model):
  
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
      
        return reverse('author-detail', args=[str(self.id)])

 
    def __str__(self):
       
        return '%s, %s' % (self.last_name, self.first_name)
    
class Perfiles(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
    )
    dni = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    localidad = models.CharField(max_length=50, null=True)
    provincia = models.CharField(max_length=40)
    telefono = models.CharField(max_length=40)
    class Meta:
        permissions = (("mandar_mensajes", "Mandar mensajes"),
                       ("recibir_mensajes", "Recibir Mensajes"))
        
class Mensajes(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    destinatario = models.ForeignKey(User,on_delete=models.CASCADE, related_name="destinatario")
    cuerpo_mensaje = models.CharField(max_length=50)
    fecha_envio = models.DateField(null=True, blank=True)
    
        

    

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime #for checking renewal date range.
from django.forms import ModelForm
from .models import *
from django.core.validators import FileExtensionValidator 
from django.core.exceptions import ValidationError
import re
from django.contrib.auth.forms import UserCreationForm 

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(widget=forms.DateInput(attrs={"type":"date"}),help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data
    
class FormularioCompleto(forms.Form):
    LISTA_MASCOTAS =( 
        ("Perro", "Perro"), 
        ("Gato", "Gato"), 
        ("Camaleon", "Camaleon"), 
        ("Avispa", "Avispa"), 
    ) 
    LISTA_OCIOS=(
        ("Cine", "Cine"), 
        ("Gym", "Gym"), 
        ("Programar", "Programar"), 
        ("Cantar", "Cantar"),
    )
    LISTA_SEXO=(
        ("Hombre", "Hombre"), 
        ("Mujer", "Mujer"), 
        ("NULO", "NULO"), 
    )
    COLORES = ( 
    ("Azul", "Azul"), 
    ("Rojo", "Rojo"), 
    ("Verde", "Verde"), 
    ("Amarillo", "Amarillo"), 
    ("Rosa", "Rosa"), 
 ) 

    

    nombre = forms.CharField( max_length=30)
    apellido = forms.CharField(max_length=40)
    edad = forms.DecimalField(decimal_places=0)
    Mascota = forms.MultipleChoiceField (choices = LISTA_MASCOTAS)
    ocio=forms.MultipleChoiceField(choices=LISTA_OCIOS, widget=forms.CheckboxSelectMultiple())
    sexo = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=LISTA_SEXO, 
    )
    hora = forms.TimeField(widget=forms.DateInput(attrs={"type":"time"}))
    colores = forms.ChoiceField(choices=COLORES)
    date = forms.DateField(widget=forms.DateInput(attrs={"type":"date"}),help_text="Enter a date between now and 4 weeks (default 3).")
    libro = forms.ModelChoiceField(queryset=Book.objects.all())
    imagen = forms.ImageField()
    Observacion = forms.CharField(widget=forms.Textarea(attrs={"rows":"5"}))


# class FormularioExamen(forms.Form):
#     titulo = forms.CharField(max_length=200)
#     author = forms.ModelChoiceField(queryset=Author.objects.all())
#     summary = forms.CharField(widget=forms.Textarea(attrs={"rows":"5"}))
#     isbn = forms.CharField(max_length=13)
#     genre = forms.ModelChoiceField(queryset=Genre.objects.all())
#     portada = forms.ImageField()
#     video = forms.FileField()
#     ficheros = forms.FileField() 
#     email = forms.CharField()
 




class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
       data = self.cleaned_data['due_back']

       #Check date is not in past.
       if data < datetime.date.today():
           raise ValidationError(_('Invalid date - renewal in past'))

       #Check date is in range librarian allowed to change (+4 weeks)
       if data > datetime.date.today() + datetime.timedelta(weeks=4):
           raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

       # Remember to always return the cleaned data.
       return data
    
    class Meta:
        model = BookInstance
        fields = ['due_back',]
        labels = { 'due_back': _('Renewal date'), }
        help_texts = { 'due_back': _('Enter a date between now and 4 weeks (default 3).'), }

class FormularioExamen(forms.Form):
    titulo = forms.CharField(max_length=200)
    author = forms.ModelChoiceField(queryset=Author.objects.all())
    summary = forms.CharField(widget=forms.Textarea(attrs={"rows":"5"}))
    isbn = forms.CharField(max_length=13)
    genre = forms.ModelMultipleChoiceField(queryset=Genre.objects.all(), widget=forms.SelectMultiple,required=True)
    portada = forms.ImageField()
    video = forms.FileField(validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv'])])
    ficheros = forms.FileField()
    email = forms.EmailField()


#Aqui heredo de UserCreationForm donde incluye la password y usuario donde 
#Hashea la pass y agrego el campo email para enviarle un email
class UserCreationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email',]

class CreacionPerfilForm(forms.Form):
    users = forms.ModelChoiceField(queryset=User.objects.all())
    dni = forms.CharField(max_length=200)
    direccion = forms.CharField(max_length=50)
    localidad = forms.CharField(max_length=40)
    provincia = forms.CharField(max_length=40)
    telefono = forms.CharField(max_length=40)
    mandar_mensajes = forms.BooleanField(required=False)
    recibir_mensajes = forms.BooleanField(required=False)

class MandarMensajesForm(forms.Form):
    provincia = forms.CharField(max_length=40 ,required=False)
    localidad = forms.CharField(max_length=40, required=False)


class EnvioMensaje(forms.Form):
  
    users = forms.CharField(widget = forms.TextInput(attrs={'readonly':'readonly'}))
    nombre = forms.CharField(max_length=80)
    destinatario = forms.CharField(widget = forms.TextInput(attrs={'readonly':'readonly'}))
    cuerpo_mensaje = forms.CharField(max_length=300,widget=forms.Textarea(attrs={"rows":"5"}))
    fecha_envio = forms.DateField(widget=forms.DateInput(attrs={"type":"date"}),help_text="Fecha de Envio")





 

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Lista de Autores</h1>

         

{% if author_list %}
<ul>

    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a> ({{author.last_name}}) 
        {% if perms.catalog.can_mark_returned %}

   
        <button><a href="{% url 'author-create'  %}">Crear Autor</a></button>
        <button><a href="{% url 'author-update' author.id %}">Update Autor</a></button>
        <button><a href="{% url 'author-delete' author.id %}">Delete Autor</a></button>
        {% endif %}

    </li>
    {% endfor %}

</ul>
{% else %}
<p>No hay autores en la biblio.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<a href="{% url 'author-detail' book.author.pk %}"><strong>{{ book.author }}</strong></a>
<!-- enlace de detalle del autor aún no definido -->
<p><strong>Resumen:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Idioma:</strong> {{ book.language }}</p>
<p><strong>Genero:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}
  {% endfor%}</p>
<p><strong>Imagen</strong></p>
<img src="{{ book.portada.url }}" alt="{{ book.title }} Cover">
<h4>video</h4>
<video controls>
  <source src="{{book.video.url }}">
</video>
<h4>ficheros</h4>
{{book.ficheros}}
<div style="margin-left:20px;margin-top:20px">
  <a href="{% url 'generarPDF' book.pk %}">Generar PDF</a>
  <h4>Copias</h4>
  {% if book.ficheros.url %}
  <iframe id="iframe_pdf" src="{{ book.ficheros.url }}" style="width:800px; height:800px;" frameborder="0"></iframe>
  {%endif %}
  {% for copy in book.bookinstance_set.all %}
  <hr>
  <p
    class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
    {{ copy.get_status_display }}</p>
  {% if copy.status != 'a' %}<p><strong>Pendiente de devolución:</strong> {{copy.due_back}}</p>{% endif %}
  <p><strong>Imprimir:</strong> {{copy.imprint}}</p>
  <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
  {% endfor %}

</div>
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
<h1>GESTION LIBROS DE LA BIBLIOTECA</h1>

{% if bookinstance_list %}
<ul>

  {% for bookinst in bookinstance_list %}
  <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
    <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) --
    {{bookinst.borrower}} {% if perms.catalog.can_mark_returned %}- 
    <button class="btn btn-warning"><a
        href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a></button> {% endif %}

  </li>
  {% endfor %}
</ul>

{% else %}
<p>No hay libros prestados.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Libros prestados</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) 
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/envio_mensaje.html
{% extends "base_generic.html" %}
{% block content %}

<h1>Mandar Mensaje</h1>

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {% for field in form %}
    <p>{{field.label}}{{field}}</p>
    {% if field.errors %}
    {% for error in field.errors %}
    <p class="text-danger">El campo {{field}} es incorrecto</p>
    {% endfor %}
    {% endif %}
    {% endfor %}


</table>

  <input type="submit" value="Submit" name="Mandar Mensaje" />

  <br>





</form>

{% endblock %}

catalog/templates/catalog/formulario_creacion.html
{% extends "base_generic.html" %}
{% block content %}

<h1>Formulario Examen</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {% for field in form %}
        <p>{{field.label}}{{field}}</p>
        {% if field.errors %}
        {% for error in field.errors %}
        <p class="text-danger">El campo {{field}} es incorrecto</p>
        {% endfor %}
        {% endif %}
        {% endfor %}

    
    </table>
    <input type="submit" value="Submit" name="generar_perfil" />
   


</form>

{% endblock %}

catalog/templates/catalog/mandar_mensajes.html
{% extends "base_generic.html" %}
{% block content %}

<h1>Formulario Mensajes</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {% for field in form %}
        <p>{{field.label}}{{field}}</p>
        {% if field.errors %}
        {% for error in field.errors %}
        <p class="text-danger">El campo {{field}} es incorrecto</p>
        {% endfor %}
        {% endif %}
        {% endfor %}


    </table>
    {% if users %}

    {% for ele in users %}
    <ul>
        <li>{{ele}} {{ele.email}}
            {% if 'catalog.recibir_mensajes' in ele.get_all_permissions %}
            <a href="{% url 'gestion_mensaje' ele.pk %}">Mandar Mensajes</a> 
            {% endif %}
        </li>
    </ul>
    {% endfor %}
    {% endif %}
    <br>
    <input type="submit" value="Submit" name="generar_perfil" />



</form>

{% endblock %}

catalog/templates/catalog/mensajes_admin.html
{% extends "base_generic.html" %}

{% block content %}

{% if mensajes_list %}
<ul>

    {% for mensajes in mensajes_list %}
    <h1>Mensaje de {{mensajes.user}}</h1>
    <li> User:{{ mensajes.user }} </li>
    <li> Nombre:({{mensajes.nombre}})</li>
    <li> Destinatario:({{mensajes.destinatario}})</li>
    <li> Cuerpo:({{mensajes.cuerpo_mensaje}})</li>
    <li> Fecha_Envio:({{mensajes.fecha_envio}}) </li>
    <a href="{% url 'mensajes-delete' mensajes.pk %}">Delete</a>
    <a href="{% url 'mensajes-update' mensajes.pk %}">Update</a>

    {% endfor %}
    



</ul>
{% else %}
<p>No Mensajes Papi.</p>
{% endif %}


{% endblock %}

catalog/templates/catalog/mensajes_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ mensajes.user }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/mensajes_form.html
{% extends "base_generic.html" %}

{% block content %}
<h2>UPDATE</h2>
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/register.html
{% extends "base_generic.html" %}

{% block title %}
{% endblock %}

{% block content %}
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
{% endblock %}